services:
 ds-pingdev:
   build: ds
   image: local/pingdev-ds:8.0.0
   container_name: ds.pingdev.local
   environment:
     - DS_SET_UID_ADMIN_AND_MONITOR_PASSWORDS=true
     - DS_UID_ADMIN_PASSWORD=password
     - DS_UID_MONITOR_PASSWORD=password
   ports:
     - 636:1636
   volumes:
     - pingdev-ds-data:/opt/opendj/data
     - ./security/ds:/opt/opendj/secrets
   command: start-ds
 am:
   build: 
    context: am
    args: 
      AM_FILE_NAME: ${AM_FILE_NAME}
      AMSTER_FILE_NAME: ${AMSTER_FILE_NAME}
      FQDN: ${FQDN}
   image: local/pingdev-am:8.0.1
   container_name: am.pingdev.local
   environment:
     - FQDN=${FQDN}
     - AM_PROTOCOL=https
     - AM_PORT=8443
     - AM_ADMIN_PWD=password
     - AM_STORES_HOST=ds.pingdev.local
     - AM_STORES_PORT=1636
     - AM_STORES_PWD=password
     - AM_CFG_STORE_ADMIN_PORT=4444
     - AM_CFG_STORE_ROOT_SUFFIX=ou=am-config
     - AM_CFG_STORE_DIR_MGR=uid=am-config,ou=admins,ou=am-config
     - AM_USR_STORE_ROOT_SUFFIX=ou=identities
     - AM_USR_STORE_DIR_MGR=uid=am-identity-bind-account,ou=admins,ou=identities
     - TRUSTSTORE_PATH=/var/run/secrets/am/truststore
     - TRUSTSTORE_PIN_PATH=/var/run/secrets/am/truststore.pin
   extra_hosts:
      - "${FQDN}:127.0.0.1"
   ports:
     - 8081:8080
     - 8443:8443
   volumes:
     - ./security/am:/var/run/secrets
     - pingdev-am-config:/home/forgerock/openam
volumes:
 pingdev-ds-data:
 pingdev-am-config: